apiVersion: v1
kind: ConfigMap
metadata:
  name: msvc-usuarios
data:
  port: "8001"
  db_host: "mysql-db:3306"
  db_database: "msvc_usuarios"
#  db_username: "mysql"
#  db_password: "mysql"
#  db_root_password: "root"
  cursos_url: "msvc-cursos:8002"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: msvc-cursos
data:
  port: "8002"
  db_host: "postgres-db:5432"
  db_database: "msvc_cursos"
#  db_username: "postgres"
#  db_password: "postgres"
  usuarios_url: "msvc-usuarios:8001"
