apiVersion: apps/v1
kind: Deployment
metadata:
  name: msvc-cursos
spec:
  replicas: 3
  selector:
    matchLabels:
      app: msvc-cursos
  template:
    metadata:
      labels:
        app: msvc-cursos
    spec:
      automountServiceAccountToken: false
      containers:
        - image: yvancho/cursos:latest
          name: cursos
          ports:
            - containerPort: 8002
          env:
            - name: PORT
              value: "8002"
            - name: DB_HOST
              value: postgres-db:5432
            - name: DB_DATABASE
              value: msvc_cursos
            - name: DB_USERNAME
              value: postgres
            - name: DB_PASSWORD
              value: postgres
            - name: USUARIOS_URL
              value: msvc-usuarios:8001
