apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db

spec:
  replicas: 1
  selector:
    matchLabels:
      role: postgres-db
  template:
    metadata:
      labels:
        role: postgres-db
    spec:
      automountServiceAccountToken: false
      containers:
        - image: postgres:latest
          name: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: msvc_cursos
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-data
      volumes:
        - name: postgres-data
          hostPath:
            path: /var/lib/postgresql/data
            type: DirectoryOrCreate
