version: '3.9'

services:
  postgres-db:
    container_name: postgres-db
    image: postgres:latest
    ports:
      - "5532:5432"
    environment:
      POSTGRES_DB: msvc_cursos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
    networks:
      - spring
  msvc-cursos:
    container_name: msvc-cursos
    image: yvancho/cursos:latest
    ports:
      - "8002:8002"
    environment:
      PORT: 8002
      DB_HOST: postgres-db:5432
      DB_DATABASE: msvc_cursos
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      USUARIOS_URL: ec2-54-162-49-187.compute-1.amazonaws.com:8001
    depends_on:
      - postgres-db
      - msvc-usuarios
    networks:
      - spring

volumes:
  postgres-data:
    name: postgres-data

networks:
  spring:
    name: spring
