version: '3.9'

services:
  mysql-db:
    container_name: mysql-db
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: msvc_usuarios
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
    networks:
      - spring

  msvc-usuarios:
    container_name: msvc-usuarios
    image: yvancho/usuarios:latest
    ports:
      - "8001:8001"
    environment:
      PORT: 8001
      DB_HOST: mysql-db:3306
      DB_DATABASE: msvc_usuarios
      DB_USERNAME: mysql
      DB_PASSWORD: mysql
      CURSOS_URL: ec2-54-172-191-12.compute-1.amazonaws.com:8002
    depends_on:
      - mysql-db
    networks:
      - spring

volumes:
  mysql-data:
    name: mysql-data

networks:
  spring:
    name: spring
