version: '3.8'

services:
  mysql-db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: msvc_usuarios
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    expose:
      - '3306'
    volumes:
      - mysql-data:/var/lib/mysql

  postgres-db:
    image: postgres:latest
    environment:
      POSTGRES_DB: msvc_cursos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  mysql-data:
  postgres-data:
