version: '3.9'

services:
  mysql-db:
    container_name: mysql-db
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: msvc_usuarios
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
    networks:
      - spring

  postgres-db:
    container_name: postgres-db
    image: postgres:latest
    ports:
      - "5532:5432"
    environment:
      POSTGRES_DB: msvc_cursos
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
    networks:
      - spring

  msvc-usuarios:
    container_name: msvc-usuarios
    image: yvancho/usuarios:latest
#    image: usuarios:latest
#    build:
#      context: ./
#      dockerfile: ./msvc-usuarios/Dockerfile
    ports:
      - "8001:8001"
    env_file: ./msvc-usuarios/.env
    depends_on:
      - mysql-db
    networks:
      - spring

  msvc-cursos:
    container_name: msvc-cursos
    image: yvancho/cursos:latest
#    image: cursos:latest
#    build:
#      context: ./
#      dockerfile: ./msvc-cursos/Dockerfile
    ports:
      - "8002:8002"
    env_file: ./msvc-cursos/.env
    depends_on:
      - postgres-db
      - msvc-usuarios
    networks:
      - spring

volumes:
  mysql-data:
    name: mysql-data
  postgres-data:
    name: postgres-data

networks:
  spring:
    name: spring
