apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc

spec:
  volumeName: mysql-pv
  accessModes:
#    - ReadWriteOnce
    - ReadWriteMany
#  storageClassName: standard
  storageClassName: ""
  resources:
    requests:
      storage: 2Gi
