apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  storageClassName: ""
#  storageClassName: standard
  accessModes:
#    - ReadWriteOnce
    - ReadWriteMany
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0030343bb14857b14
#  hostPath:
#    path: /var/lib/mysql
#    type: DirectoryOrCreate
