apiVersion: v1
kind: Secret
metadata:
  name: msvc-usuarios
type: Opaque
data:
  root: cm9vdA==
  username: bXlzcWw=
  password: bXlzcWw=

---
apiVersion: v1
kind: Secret
metadata:
  name: msvc-cursos
type: Opaque
data:
  username: cG9zdGdyZXM=
  password: cG9zdGdyZXM=
